#!/usr/bin/env nextflow 
params.timeout = 10 
params.exit = 0
params.cmd = """
             # Tellus diam faucibus montes non convallis nascetur ridiculus. Nulla rutrum dictumst platea aptent quisque ipsum lobortis. Lacinia turpis purus finibus volutpat ornare hac. Aptent suscipit phasellus urna velit varius euismod aenean. Pretium mollis convallis, nostra consectetur himenaeos id potenti blandit. Blandit velit ligula, cursus cras donec hendrerit nam facilisi. Ultrices libero vulputate quis non sed mi. Morbi vitae blandit vitae ullamcorper; tincidunt vivamus magna. Sem etiam a consectetur, imperdiet litora enim eget hac tristique. Litora efficitur consectetur placerat leo rhoncus ultricies netus.
             # Interdum eros primis risus ornare egestas diam et. Nisl condimentum posuere ultrices ligula integer; primis inceptos. Blandit hendrerit vivamus ac tincidunt augue amet maecenas. Pulvinar fusce id pretium; odio primis etiam tempor. Pulvinar iaculis faucibus egestas himenaeos laoreet vitae lobortis orci. Maecenas a ridiculus pellentesque bibendum iaculis dolor lacinia. Ut tempus vehicula mus, libero auctor vestibulum. Massa taciti nulla aliquam metus suspendisse turpis dignissim. Luctus fringilla vulputate nisi rutrum tempus orci bibendum dignissim. Feugiat orci cubilia vehicula elit mollis enim nam erat turpis.
             # Adipiscing sapien tincidunt phasellus sem elementum. Quisque ligula massa; duis facilisi nunc hac. Libero non donec sociosqu ipsum nunc cras cursus porta. Tortor habitasse nostra ante primis pellentesque natoque nullam nec. Lacinia potenti nullam habitasse neque nec. Felis dolor congue potenti justo nec class fames fermentum felis. Sagittis lacinia fringilla sociosqu potenti sem maecenas cursus libero. Ipsum a sollicitudin nisl; purus et et.
             # Suspendisse et eleifend magna sollicitudin; pharetra eget. Id dapibus potenti ex mattis massa eu. Dictum consectetur lacinia; facilisis magna magnis hac porttitor inceptos porta. Cursus magna sollicitudin pellentesque egestas dapibus rhoncus eros. Etiam massa congue nibh, conubia posuere blandit. Torquent odio faucibus convallis congue aptent ex lobortis gravida magnis. Penatibus luctus phasellus nec volutpat ullamcorper massa et. Venenatis augue mus aliquet himenaeos quis.
             # Quisque sagittis torquent morbi enim mi scelerisque dignissim? Natoque sapien nec conubia cubilia cursus mi varius sagittis turpis. Ut sem elit mollis; urna vel tempor. Eu posuere cursus, iaculis ridiculus et accumsan porttitor. Semper suspendisse ex velit quam ultricies risus in. Euismod etiam ultrices aliquet malesuada maximus. Venenatis nunc mollis sociosqu nisl velit curae.
             # Montes adipiscing semper porttitor habitant efficitur aptent lacus. Nulla donec erat odio iaculis ridiculus pharetra. Finibus parturient pharetra velit blandit leo luctus taciti. Habitasse id nostra nulla; nascetur consectetur egestas dis senectus. Accumsan blandit justo non magnis lorem. Tincidunt tellus finibus vehicula; mattis curae tincidunt torquent.
             # Per ut inceptos rutrum penatibus finibus litora. Eu lorem class porttitor sodales aliquet ipsum eros venenatis arcu. Ridiculus lectus metus erat elit magnis porta. Massa lobortis inceptos praesent; magna hendrerit dictum phasellus. Facilisis cras sociosqu vehicula vulputate eu; eleifend feugiat venenatis. Maecenas sed mi at libero rutrum. Lacus ridiculus nisl taciti; faucibus taciti class. Amet fusce metus condimentum efficitur bibendum iaculis ut etiam? Neque duis urna auctor porttitor mauris luctus.
             # Luctus id feugiat at nulla, potenti penatibus bibendum nisl. Duis montes natoque congue lacinia, conubia condimentum consectetur aptent taciti. Laoreet sociosqu congue magnis varius at sed felis ridiculus. Diam erat elit eleifend pretium volutpat. Mauris cras accumsan hendrerit donec varius. Justo condimentum laoreet volutpat amet lacus; tempus interdum morbi hac.
             # Lorem nullam maximus ridiculus dis tempor maecenas mattis. Blandit penatibus ante ridiculus elit tellus convallis sociosqu magnis. Himenaeos imperdiet vel nibh risus aptent erat. Posuere interdum ullamcorper elit; praesent posuere hac faucibus magnis nisl. Parturient pellentesque euismod dolor tellus fringilla. Euismod ligula imperdiet leo sem lorem vestibulum ridiculus mollis vestibulum.
             # Cras habitant tempus nec vehicula donec class magna. Neque imperdiet phasellus per nostra porttitor nostra. Interdum platea luctus amet finibus pellentesque nibh. Condimentum auctor elementum dis quisque felis vitae. Suscipit nisl massa mauris cras enim condimentum nisi. Tristique parturient amet donec habitant sociosqu ex quam neque.
             # Donec erat condimentum cubilia vel faucibus. Mus in sodales enim nisi fusce mattis euismod lacinia sem. Dapibus aliquam commodo sodales, fusce venenatis nam. Commodo etiam tristique torquent cras; ligula fames integer. Sodales facilisis orci gravida massa lobortis porta nibh montes. Ultrices mattis pretium erat maximus taciti. Feugiat metus porttitor vulputate nisl natoque. Feugiat hendrerit taciti; semper taciti pharetra pretium aenean nullam vestibulum. Nostra finibus ut malesuada non himenaeos faucibus.
             # Imperdiet iaculis ornare sapien efficitur inceptos. Non hac metus enim cursus magnis vestibulum maecenas. Interdum pharetra habitant platea laoreet tellus mi? Platea cursus elit vivamus lacinia dolor morbi cubilia. Varius ac primis scelerisque duis eros augue. Magnis suscipit cubilia senectus, per in sociosqu. Mi ac ligula blandit nibh cursus cursus eu habitasse est.
             # Fermentum ligula penatibus hendrerit fames felis. Habitasse ridiculus quis sodales congue libero; elementum hac. Pellentesque dis sodales convallis tortor maximus sociosqu sociosqu gravida. Litora dui curabitur parturient mattis vulputate justo? Etiam maximus hendrerit eu aptent litora eros quisque molestie ad. Euismod sed nostra metus amet sapien. Cubilia non vestibulum vestibulum et urna; purus fusce. Dignissim varius vel arcu litora ligula lacus?
             # Senectus volutpat orci tempor laoreet amet. Varius hac auctor platea suscipit sed ac. Tincidunt hendrerit consectetur ad pharetra convallis. Sagittis tempor dictum cursus nisi praesent; nisi litora nunc. Eget dolor sagittis sed tempor himenaeos viverra habitasse. Vulputate magnis ad rutrum sit dictumst faucibus sodales fringilla nulla. Justo aliquet volutpat litora morbi efficitur congue. Est facilisis risus tristique eros penatibus phasellus mi molestie.
             # Dui lectus ex conubia aenean diam in integer odio erat. Mus id eu hac habitasse vestibulum. Inceptos hac luctus iaculis sit cursus per lorem. Sollicitudin lectus facilisis ligula eget penatibus dis? Posuere mattis egestas sagittis at ullamcorper porta consectetur. Ex dignissim torquent volutpat ac odio sociosqu nisi quis. Id dictumst tristique dis consectetur condimentum vivamus scelerisque. Lorem vestibulum ante tincidunt dui ac diam sagittis.
             # Dolor imperdiet vulputate dapibus velit class ultricies per. Mi ultricies maecenas feugiat urna conubia risus faucibus. Vel egestas morbi mauris finibus parturient sem fusce torquent venenatis. Volutpat per ultrices ullamcorper lectus sagittis dui quis. Rutrum et aenean tellus vel eros. Elit phasellus risus lacus, porttitor metus dapibus in aliquet. Ante lacinia iaculis nulla fames platea quisque sodales potenti. Viverra mollis netus neque at semper nunc; ultricies litora. Mattis cras fringilla integer cras tempor phasellus.
             # Hendrerit velit a turpis aptent, diam maecenas ultrices. Nulla ornare vehicula dui eleifend nam. Elit convallis turpis; etiam elementum sociosqu lacus suscipit. Diam morbi tortor massa ultrices aptent tempus ultrices tristique. Libero auctor class est montes magna ac. Libero posuere vitae dignissim, nulla mollis facilisis laoreet. Risus ridiculus ullamcorper pellentesque varius senectus venenatis pellentesque. Euismod mauris hac iaculis tincidunt iaculis.
             # Blandit dis sed aliquet vivamus posuere rhoncus mollis sem. Ultrices praesent lectus faucibus; dignissim ipsum augue. Aenean curabitur elit gravida consequat imperdiet phasellus. Potenti aliquet efficitur aliquam cubilia maximus tortor. Erat amet nascetur fusce urna enim fermentum eros. Libero blandit risus a fringilla vestibulum luctus lobortis magnis? Mus a elit pulvinar; varius mattis nisi suscipit. Gravida elit sed dapibus dictum vitae. Netus ac libero augue ligula sem mauris purus.
             # Tempus potenti ac sociosqu magnis nulla ornare in! Nascetur diam mauris semper, felis faucibus id nullam lacus congue. Tempor morbi quam porttitor vivamus integer eget commodo risus. Dapibus hac purus laoreet ex fames. Class quam curabitur tempor fusce primis. Facilisis dui inceptos dolor sodales facilisis vivamus praesent. Sociosqu mauris dolor suspendisse finibus aptent? Nullam convallis nostra rhoncus parturient mattis malesuada. Non et duis fusce vestibulum at conubia class inceptos.
             # Congue habitant imperdiet maecenas class neque sed. Consequat erat gravida semper maecenas pretium amet sit. Dictumst scelerisque ullamcorper id; integer leo duis. Varius sed augue purus varius inceptos aptent. Euismod dictumst nibh leo placerat; accumsan netus. Primis nostra proin condimentum senectus vitae arcu maecenas. Taciti rhoncus posuere ipsum mattis ut curae interdum tristique torquent. Primis finibus tellus mi vivamus vel primis ultrices. Porttitor lorem diam vel commodo ex volutpat auctor.
             # Aenean primis suscipit, malesuada parturient faucibus at vulputate commodo. Vestibulum malesuada sapien est auctor ac tellus facilisi. Ultricies massa diam ad litora dui mattis? Natoque vel vestibulum quis gravida; nascetur suscipit elementum. In quam ad dignissim faucibus tellus hac. Elit venenatis ac facilisi sagittis himenaeos praesent nisl risus. Fringilla penatibus maximus elementum vitae magna molestie? Suspendisse pharetra in vitae nec non montes sociosqu.
             echo 'Hello (timeout $params.timeout)'"""
params.times = 1
params.forks = 1

process foo {
  maxForks params.forks
  input: val(x)
  /
  bash -c "$params.cmd"
  sleep $params.timeout
  exit $params.exit
  /
}

workflow {
  channel.of(1..params.times) | foo
}
